### ISSUE TITLE
options :nullable are unknown

### ISSUE THREAD

**Issue by 1xch** [datamapper/dm-tags#12]
Just updating an application to work with 3.1/1.2.0.rc1

this only comes up when dm-tags is installed

```
rake db:automigrate --trace  
rake aborted!
options :nullable are unknown
/home/qx/.rvm/gems/ruby-1.9.2-p180/gems/dm-core-1.2.0.rc1/lib/dm-core/property.rb:777:in `assert_valid_options'
/home/qx/.rvm/gems/ruby-1.9.2-p180/gems/dm-core-1.2.0.rc1/lib/dm-core/property.rb:743:in `initialize'
/home/qx/.rvm/gems/ruby-1.9.2-p180/gems/dm-core-1.2.0.rc1/lib/dm-core/property/numeric.rb:16:in `initialize'
/home/qx/.rvm/gems/ruby-1.9.2-p180/gems/dm-core-1.2.0.rc1/lib/dm-core/property/integer.rb:15:in `initialize'
/home/qx/.rvm/gems/ruby-1.9.2-p180/gems/dm-core-1.2.0.rc1/lib/dm-core/model/property.rb:55:in `new'
/home/qx/.rvm/gems/ruby-1.9.2-p180/gems/dm-core-1.2.0.rc1/lib/dm-core/model/property.rb:55:in `property'
/home/qx/.rvm/gems/ruby-1.9.2-p180/gems/dm-validations-1.2.0.rc1/lib/dm-validations/auto_validate.rb:11:in `property'
/home/qx/.rvm/gems/ruby-1.9.2-p180/gems/dm-tags-0.10.0/lib/dm-tags/tagging.rb:5:in `<class:Tagging>'
/home/qx/.rvm/gems/ruby-1.9.2-p180/gems/dm-tags-0.10.0/lib/dm-tags/tagging.rb:1:in `<top (required)>'
/home/qx/.rvm/gems/ruby-1.9.2-p180/gems/dm-tags-0.10.0/lib/dm-tags.rb:1:in `require'
/home/qx/.rvm/gems/ruby-1.9.2-p180/gems/dm-tags-0.10.0/lib/dm-tags.rb:1:in `<top (required)>'
/home/qx/.rvm/gems/ruby-1.9.2-p180/gems/bundler-1.0.18/lib/bundler/runtime.rb:68:in `require'
/home/qx/.rvm/gems/ruby-1.9.2-p180/gems/bundler-1.0.18/lib/bundler/runtime.rb:68:in `block (2 levels) in require'
/home/qx/.rvm/gems/ruby-1.9.2-p180/gems/bundler-1.0.18/lib/bundler/runtime.rb:66:in `each'
/home/qx/.rvm/gems/ruby-1.9.2-p180/gems/bundler-1.0.18/lib/bundler/runtime.rb:66:in `block in require'
/home/qx/.rvm/gems/ruby-1.9.2-p180/gems/bundler-1.0.18/lib/bundler/runtime.rb:55:in `each'
/home/qx/.rvm/gems/ruby-1.9.2-p180/gems/bundler-1.0.18/lib/bundler/runtime.rb:55:in `require'
/home/qx/.rvm/gems/ruby-1.9.2-p180/gems/bundler-1.0.18/lib/bundler.rb:120:in `require'
/media/essential/projects/1_current/thrisp/modules/+velicessegia/ticketenginealpha/config/application.rb:13:in `<top (required)>'
/home/qx/.rvm/rubies/ruby-1.9.2-p180/lib/ruby/site_ruby/1.9.1/rubygems/custom_require.rb:36:in `require'
/home/qx/.rvm/rubies/ruby-1.9.2-p180/lib/ruby/site_ruby/1.9.1/rubygems/custom_require.rb:36:in `require'
/media/essential/projects/1_current/thrisp/modules/+velicessegia/ticketenginealpha/Rakefile:5:in `<top (required)>'
/home/qx/.rvm/gems/ruby-1.9.2-p180/gems/rake-0.9.2/lib/rake/rake_module.rb:25:in `load'
/home/qx/.rvm/gems/ruby-1.9.2-p180/gems/rake-0.9.2/lib/rake/rake_module.rb:25:in `load_rakefile'
/home/qx/.rvm/gems/ruby-1.9.2-p180/gems/rake-0.9.2/lib/rake/application.rb:495:in `raw_load_rakefile'
/home/qx/.rvm/gems/ruby-1.9.2-p180/gems/rake-0.9.2/lib/rake/application.rb:78:in `block in load_rakefile'
/home/qx/.rvm/gems/ruby-1.9.2-p180/gems/rake-0.9.2/lib/rake/application.rb:129:in `standard_exception_handling'
/home/qx/.rvm/gems/ruby-1.9.2-p180/gems/rake-0.9.2/lib/rake/application.rb:77:in `load_rakefile'
/home/qx/.rvm/gems/ruby-1.9.2-p180/gems/rake-0.9.2/lib/rake/application.rb:61:in `block in run'
/home/qx/.rvm/gems/ruby-1.9.2-p180/gems/rake-0.9.2/lib/rake/application.rb:129:in `standard_exception_handling'
/home/qx/.rvm/gems/ruby-1.9.2-p180/gems/rake-0.9.2/lib/rake/application.rb:59:in `run'
/home/qx/.rvm/gems/ruby-1.9.2-p180/gems/rake-0.9.2/bin/rake:32:in `<top (required)>'
/home/qx/.rvm/gems/ruby-1.9.2-p180/bin/rake:19:in `load'
/home/qx/.rvm/gems/ruby-1.9.2-p180/bin/rake:19:in `<main>'
```

**Comment by 1xch** [comment]
eh, adding DM_VERSION to the gemfile specification for the gem seems to resolve.
